### PR TITLE
test-bot-docker: git config user.name and user.email

### PR DESCRIPTION
**Pull request by sjackman**
When used with a pull request URL, fix the error:
Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I suggest using `git config --global user.name` and `git config --global user.email`

**Comment by maxim-belkin** [comment]
oh, too late...

**Comment by sjackman** [comment]
Do you mean fetch the values of the host and pass them to Docker?

**Comment by maxim-belkin** [comment]
yes.

**Comment by sjackman** [comment]
I don't think the value of these variables actually get used by `brew test-bot`. The `brew pull` command does `git am` which should use the values from the commits in the PR. I'm thinking that I'd rather not import variables from the host if possible, to make it less dependent on the host environment.

**Pull request merged**
